# Generated by Django 2.2.6 on 2019-10-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=50, unique=True)),
                ('cus_name_en', models.CharField(max_length=50, null=True)),
                ('cus_id', models.CharField(max_length=50)),
                ('cus_idcard', models.CharField(max_length=50)),
                ('cus_sex', models.CharField(max_length=50)),
                ('cus_phone1', models.CharField(max_length=50)),
                ('cus_phone2', models.CharField(max_length=50, null=True)),
                ('cus_addr1', models.CharField(max_length=50)),
                ('cus_addr2', models.CharField(max_length=50)),
                ('cus_email', models.CharField(max_length=50, null=True)),
                ('cus_bd', models.DateField()),
                ('cus_shop_id', models.CharField(max_length=50)),
                ('cus_arr_date', models.DateField()),
                ('cus_source', models.CharField(max_length=50, null=True)),
                ('cus_remark', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
