# Generated by Django 2.2.6 on 2019-10-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cus_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_name',
            field=models.CharField(max_length=50),
        ),
    ]
