# Generated by Django 2.2.6 on 2019-10-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0003_auto_20191022_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cus_class',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_arr_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_bd',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_sex',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
