# Generated by Django 2.2.6 on 2019-10-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0004_auto_20191023_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cus_addr1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_addr2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_bd',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_idcard',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_shop_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
