# Generated by Django 2.2.6 on 2019-10-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0005_auto_20191024_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cus_remark',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
