# Generated by Django 2.2.6 on 2019-10-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0006_auto_20191024_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cus_seeable',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
