# Generated by Django 2.2.6 on 2019-10-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0007_customer_cus_seeable'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogedIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loged_user', models.CharField(max_length=50)),
                ('loged_ip', models.CharField(max_length=50)),
            ],
        ),
    ]
