# Generated by Django 2.2.6 on 2019-10-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0008_logedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=50, unique=True)),
                ('emp_name_ch', models.CharField(max_length=50)),
                ('emp_name_en', models.CharField(max_length=50, null=True)),
                ('emp_idcard', models.CharField(max_length=50, null=True)),
                ('emp_class', models.CharField(max_length=50)),
                ('emp_salary', models.IntegerField()),
                ('emp_bd', models.CharField(max_length=50)),
                ('emp_arr_date', models.CharField(max_length=50)),
                ('emp_leave_date', models.CharField(max_length=50)),
                ('emp_shop_id', models.CharField(max_length=50)),
                ('emp_phone1', models.CharField(max_length=50)),
                ('emp_phone2', models.CharField(max_length=50, null=True)),
                ('emp_addr1', models.CharField(max_length=50, null=True)),
                ('emp_addr2', models.CharField(max_length=50, null=True)),
                ('emp_email', models.EmailField(max_length=254, null=True)),
                ('emp_remark', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
