# Generated by Django 2.2.6 on 2019-10-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0009_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_seeable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_seeable',
            field=models.BooleanField(default=True),
        ),
    ]
