# Generated by Django 2.2.6 on 2019-11-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0011_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instock_id', models.CharField(max_length=50)),
                ('insock_shop_id', models.CharField(max_length=50)),
                ('instock_qua', models.IntegerField()),
                ('instock_salesvolume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_type', models.CharField(max_length=50)),
                ('stock_id', models.CharField(max_length=50, unique=True)),
                ('stock_name', models.CharField(max_length=50)),
                ('stock_price', models.IntegerField()),
                ('stock_cost', models.IntegerField()),
                ('stock_point', models.IntegerField()),
                ('stock_remark', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
