# Generated by Django 2.2.6 on 2019-11-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0012_instock_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instock',
            name='instock_qua',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='instock',
            name='instock_salesvolume',
            field=models.IntegerField(default=0),
        ),
    ]
