# Generated by Django 2.2.6 on 2019-11-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0013_auto_20191108_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ir_id', models.CharField(max_length=50)),
                ('ir_date', models.CharField(max_length=50)),
                ('ir_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImportStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ir_id', models.CharField(max_length=50)),
                ('is_stock_id', models.CharField(max_length=50)),
                ('is_qua', models.IntegerField()),
                ('is_from_shop_id', models.CharField(max_length=50)),
            ],
        ),
    ]
