# Generated by Django 2.2.6 on 2019-11-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0014_importreport_importstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='importreport',
            name='ir_remark',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
