# Generated by Django 2.2.6 on 2019-11-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0015_importreport_ir_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_cost',
            field=models.IntegerField(null=True),
        ),
    ]
