# Generated by Django 2.2.6 on 2019-11-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0016_auto_20191110_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_point',
            field=models.IntegerField(null=True),
        ),
    ]
