# Generated by Django 2.2.6 on 2019-11-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0017_auto_20191110_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instock',
            old_name='insock_shop_id',
            new_name='instock_shop_id',
        ),
    ]
