# Generated by Django 2.2.6 on 2019-11-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0018_auto_20191111_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_seeable',
            field=models.BooleanField(default=True),
        ),
    ]
