# Generated by Django 2.2.6 on 2019-11-12 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0019_stock_stock_seeable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_id', models.CharField(max_length=50)),
                ('sale_date', models.CharField(max_length=50)),
                ('sale_stock_price_total', models.IntegerField()),
                ('sale_price_total', models.IntegerField()),
                ('sale_point', models.IntegerField()),
                ('sale_pay', models.CharField(max_length=50)),
                ('sale_type', models.CharField(max_length=50)),
                ('sale_remark', models.CharField(max_length=50)),
                ('sale_created_by_user_id', models.CharField(max_length=50)),
                ('sale_modified_by_user_id', models.CharField(max_length=50)),
                ('sale_cus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinal.Customer')),
                ('sale_person_in_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinal.Employee')),
                ('sale_shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinal.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='Salestock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salestock_price', models.IntegerField()),
                ('salestock_amount', models.IntegerField()),
                ('salestock_sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinal.Sale')),
                ('salestock_stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinal.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Salealloc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salealloc_point', models.IntegerField()),
                ('salealloc_prec', models.IntegerField()),
                ('salealloc_emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinal.Employee')),
                ('salealloc_sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinal.Sale')),
                ('salealloc_stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinal.Stock')),
            ],
        ),
    ]
