# Generated by Django 2.2.6 on 2019-11-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0021_auto_20191113_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_complete',
            field=models.BooleanField(default=False),
        ),
    ]
