# Generated by Django 2.2.6 on 2019-11-14 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0023_auto_20191114_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salealloc',
            old_name='salealloc_prec',
            new_name='salealloc_perc',
        ),
    ]
