# Generated by Django 2.2.6 on 2019-11-14 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0024_auto_20191114_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salealloc',
            old_name='salealloc_emp_id',
            new_name='salealloc_emp',
        ),
    ]
