# Generated by Django 2.2.6 on 2019-11-21 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0026_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='serv_modified_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_this_user_serv', to='appFinal.User'),
        ),
    ]
