# Generated by Django 2.2.6 on 2019-11-21 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0027_auto_20191121_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='serv_person_in_charge',
        ),
        migrations.RemoveField(
            model_name='service',
            name='serv_shop_id',
        ),
        migrations.AddField(
            model_name='service',
            name='serv_shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appFinal.Shop'),
        ),
    ]
