# Generated by Django 2.2.6 on 2019-11-26 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0028_auto_20191121_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuscl_quantity', models.IntegerField()),
                ('cuscl_cus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinal.Customer')),
                ('cuscl_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinal.Stock')),
            ],
        ),
    ]
