# Generated by Django 2.2.6 on 2019-12-12 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0029_customerclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_name', models.CharField(max_length=50)),
                ('comm_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MultiSevicePercent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MSP_name', models.CharField(max_length=50)),
                ('MSP_code', models.CharField(max_length=50)),
                ('MSP_emp1', models.IntegerField()),
                ('MSP_emp2', models.IntegerField()),
                ('MSP_emp3', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegularBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_name', models.CharField(max_length=50)),
                ('bonus_code', models.CharField(max_length=50)),
                ('bonus_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SalaryResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SR_emp_name', models.CharField(max_length=50)),
                ('SR_salary', models.IntegerField()),
                ('SR_point', models.IntegerField()),
                ('SR_point1', models.IntegerField()),
                ('SR_point2', models.IntegerField()),
                ('SR_point3', models.IntegerField()),
                ('SR_stock_income_comm', models.IntegerField()),
                ('SR_income', models.IntegerField()),
                ('SRSCIncomeComm', models.IntegerField()),
                ('SRSCIncome', models.IntegerField()),
                ('SRbarberIncomeComm', models.IntegerField()),
                ('SRbarberIncome', models.IntegerField()),
                ('SRresult', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SalarySelectEmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSE_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinal.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='CommLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CL_income_limit', models.IntegerField()),
                ('CL_bonus_perc', models.IntegerField()),
                ('CL_comm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinal.Commission')),
            ],
        ),
    ]
