# Generated by Django 2.2.6 on 2019-12-12 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0031_commission_comm_income_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommIncomeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CIT_type', models.CharField(max_length=50)),
                ('CIT_comm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinal.Commission')),
            ],
        ),
    ]
